/* Auto-generated by genmsg_cpp for file /home/paralax2/fuerte_workspace/sandbox/eddiebot/eddiebot_node/msg/Eddie.msg */
#ifndef EDDIEBOT_NODE_MESSAGE_EDDIE_H
#define EDDIEBOT_NODE_MESSAGE_EDDIE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace eddiebot_node
{
template <class ContainerAllocator>
struct Eddie_ {
  typedef Eddie_<ContainerAllocator> Type;

  Eddie_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  Eddie_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef float _linear_type;
  float linear;

  typedef float _angular_type;
  float angular;


  typedef boost::shared_ptr< ::eddiebot_node::Eddie_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eddiebot_node::Eddie_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Eddie
typedef  ::eddiebot_node::Eddie_<std::allocator<void> > Eddie;

typedef boost::shared_ptr< ::eddiebot_node::Eddie> EddiePtr;
typedef boost::shared_ptr< ::eddiebot_node::Eddie const> EddieConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::eddiebot_node::Eddie_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::eddiebot_node::Eddie_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace eddiebot_node

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::eddiebot_node::Eddie_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::eddiebot_node::Eddie_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::eddiebot_node::Eddie_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const  ::eddiebot_node::Eddie_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9d5c2dcd348ac8f7ULL;
  static const uint64_t static_value2 = 0x6ce2a4307bd63a13ULL;
};

template<class ContainerAllocator>
struct DataType< ::eddiebot_node::Eddie_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eddiebot_node/Eddie";
  }

  static const char* value(const  ::eddiebot_node::Eddie_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::eddiebot_node::Eddie_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 linear\n\
float32 angular\n\
";
  }

  static const char* value(const  ::eddiebot_node::Eddie_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::eddiebot_node::Eddie_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::eddiebot_node::Eddie_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Eddie_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eddiebot_node::Eddie_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::eddiebot_node::Eddie_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDDIEBOT_NODE_MESSAGE_EDDIE_H

