(cl:defpackage eddiebot_node-srv
  (:use )
  (:export
   "SETEDDIEBOTMODE"
   "<SETEDDIEBOTMODE-REQUEST>"
   "SETEDDIEBOTMODE-REQUEST"
   "<SETEDDIEBOTMODE-RESPONSE>"
   "SETEDDIEBOTMODE-RESPONSE"
   "SETDIGITALOUTPUTS"
   "<SETDIGITALOUTPUTS-REQUEST>"
   "SETDIGITALOUTPUTS-REQUEST"
   "<SETDIGITALOUTPUTS-RESPONSE>"
   "SETDIGITALOUTPUTS-RESPONSE"
  ))

