(cl:defpackage eddiebot_node-msg
  (:use )
  (:export
   "<EDDIESENSORSTATE>"
   "EDDIESENSORSTATE"
   "<DRIVE>"
   "DRIVE"
   "<LAPTOPCHARGESTATUS>"
   "LAPTOPCHARGESTATUS"
   "<BATTERYSTATE>"
   "BATTERYSTATE"
   "<EDDIE>"
   "EDDIE"
   "<EDDIEBOTSENSORSTATE>"
   "EDDIEBOTSENSORSTATE"
   "<RAWEDDIEBOTSENSORSTATE>"
   "RAWEDDIEBOTSENSORSTATE"
  ))

